/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    UBadge: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UChangelogVersion: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/ChangelogVersion.vue')['default']
    UChangelogVersions: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/ChangelogVersions.vue')['default']
    UFileUpload: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/FileUpload.vue')['default']
  }
}
